### ISSUE TITLE
Tests on MacOS

### ISSUE THREAD

**Issue by canadaduane** [not-fl3/miniquad#10]
I'm using good-web-game, which depends on miniquad, and currently, I can't run tests on my project:

```
cargo test
   Compiling c2-chacha v0.2.3
   Compiling sapp-linux v0.1.1
   Compiling libc v0.2.66
   Compiling deflate v0.7.20
   Compiling rustc-hash v1.0.1
   Compiling num-integer v0.1.42
   Compiling num-complex v0.2.4
   Compiling num-traits v0.1.43
error: failed to run custom build command for `sapp-linux v0.1.1`

Caused by:
  process didn't exit successfully: `/Users/duane/Projects/ayanara/target/debug/build/sapp-linux-0738334df62e1ace/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'sapp_linux support only linux target', /Users/duane/.cargo/registry/src/github.com-1ecc6299db9ec823/sapp-linux-0.1.1/build.rs:7:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed
```

Is there a way I might be able to run `cargo test` on my `good-web-game`-depending game, on Mac OS X, when the tests involved don't really exercise anything related to miniquad?

**Comment by not-fl3** [comment]
Thanks for report, working on it!

**Comment by not-fl3** [comment]
Should be fixed in `0.2.7` by https://github.com/not-fl3/miniquad/commit/5b54da5dfd2f915505b94c0cca7e6c2be9d1514d

**Comment by not-fl3** [comment]
Fill free to reopen if its still broken, I cant test it on real macos unfortunately :(

**Comment by canadaduane** [comment]
Looks good! I needed to bump the dependency on `good-web-game` to `0.2.7` explicitly (not sure why `cargo update` didn't pick it up?) But I can run tests now. Thank you!
