### ISSUE TITLE
MSAA doesn't seem to work

### ISSUE THREAD

**Issue by tversteeg** [not-fl3/miniquad#109]
I'm trying to apply super sampling anti aliasing using `sample_count` in `Conf`, but it doesn't matter what value I use I always get the following result:

![2020-05-26_16-37](https://user-images.githubusercontent.com/2574730/82914176-77e67680-9f6f-11ea-8a59-c86a88d89c46.png)

This is both the case with rendering to a separate texture and using a default pass.

Tested on both Linux & WASM.

_Edit:_

I've investigated it a bit more, could it be because `GLX_SAMPLE_BUFFERS = 1` is missing [here](https://github.com/not-fl3/miniquad/blob/master/native/sapp-linux/src/lib.rs#L1086) (on Linux)?

https://www.khronos.org/opengl/wiki/Multisampling

**Comment by tversteeg** [comment]
I'm not sure what happened but it seems to work now. Thanks?

**Comment by not-fl3** [comment]
nice, bug fixed itself for the first time!

**Comment by nokola** [comment]
next: feature will write itself! :)
