### ISSUE TITLE
Access to console.log

### ISSUE THREAD

**Issue by canadaduane** [not-fl3/miniquad#12]
I see there is a [console_log function](https://github.com/not-fl3/miniquad/blob/71e429830428d0c01f19ebf1d60d3d71b0a41ab3/native/sapp-wasm/src/lib.rs#L286) in `sapp-wasm`. Is this something that could be re-exported for users of `good-web-game`? I suppose it would need to be stubbed for other `sapp-*` targets as well, or maybe even implemented as a logging function standard to each target.

Alternatively, is there another way to add this functionality? I'm quite new to wasm & rust, so would it just be a matter of building my own bindings, like you did for `gl.js`?

**Comment by not-fl3** [comment]
I want to implement [log-rs](https://github.com/rust-lang/log) backend forwarding `log` calls to `console_log`. 

Something like https://github.com/iamcodemaker/console_log, but depending on `sapp_wasm` instead of wasm_bindgen.

**Comment by canadaduane** [comment]
Ok, I'll take a look at implementing this.

**Comment by canadaduane** [comment]
Would the logging apparatus you're thinking of log to each of the `sapp-*` variants automatically, (i.e. so that a caller could just `log("whatever")` and have it work for linux, windows, wasm32) or would it be implemented only for `sapp_wasm`, and depend on the calling code to do the right thing depending on compile target?

**Comment by canadaduane** [comment]
Feedback welcome on https://github.com/not-fl3/miniquad/pull/13

**Comment by not-fl3** [comment]
Done: https://github.com/not-fl3/miniquad/wiki/Cross-platform-logs
