### ISSUE TITLE
Configuring window before start

### ISSUE THREAD

**Issue by dasifefe** [not-fl3/miniquad#16]
Is there a way already implemented to configure how the window will be created?

- Size (width, height);
- Decorated;
- Resizable;
- Title;

What about controlling the frequency of the main loop (frames per second)?

**Comment by not-fl3** [comment]
AFAIK all that window configurations are implemented by `sokol-app`, but not yet exposed to the public API. Will fix! 

For the frequency control - not implemented and not planned. Its not a native feature for most of the platforms(if not all of them), so not the miniquad's responsibility.

VSYNC control looks relevant thought, would be nice to have control over vsync in the future.

**Comment by optozorax** [comment]
How will `Resizable` and `Size` options work in browser? 
I like current option when app occupy full screen.

**Comment by AKholetsky** [comment]
Does this commit solve the issue?
https://github.com/not-fl3/miniquad/commit/9a42e03345638bfd0f7419cb2f02a8a05bbdf807

**Comment by not-fl3** [comment]
> Does this commit solve the issue?
> [9a42e03](https://github.com/not-fl3/miniquad/commit/9a42e03345638bfd0f7419cb2f02a8a05bbdf807)

It does! 
Let's open the new issue if something is missing :)
