### ISSUE TITLE
[bug][mac] high_dpi: true leads to extreme flickering

### ISSUE THREAD

**Issue by emilk** [not-fl3/miniquad#169]
macOS Mojave 10.14.6 running on an Intel MacBook Pro.

Turning on `high_dpi: true` in `examples/quad.rs` I get extreme 60Hz flicker until I resize the screen, and it all works again:

![miniquad-flicker](https://user-images.githubusercontent.com/1148717/105558189-4399a480-5d0e-11eb-8808-256e63881707.gif)

Seems like maybe there is a call to `glViewport` missing somewhere

**Comment by not-fl3** [comment]
Thanks for report, yes, looks like a wrong viewport. 
 
I definetly need to get myself a high-dpi screen at some point :D

**Comment by emilk** [comment]
> I definetly need to get myself a high-dpi screen at some point :D

Oh they are the best :)

---

So it seems `sapp_dpi_scale()` is always `1.0` on my computer until I resize the window, and then it becomes `2.0`. This makes the viewport/scissor rectangles in `begin_pass` in `graphics.rs` wrong until the resize.

**Comment by not-fl3** [comment]
> So it seems sapp_dpi_scale() is always 1.0 on my computer until I resize the window, and then it becomes 2.0. This makes the viewport/scissor rectangles in begin_pass in graphics.rs wrong until the resize.

good catch! Blind attempt to fix this: https://github.com/not-fl3/miniquad/pull/170

**Comment by emilk** [comment]
> good catch! Blind attempt to fix this: #170

Seems like you are a better coder blind than most are with their eyes open.

**Comment by not-fl3** [comment]
Published `v0.3.0-alpha.26` with a fix. 
Feel free to reopen if it is not really fixed there.
