### ISSUE TITLE
native/sapp-darwin: Implement mac clipboard

### ISSUE THREAD

**Issue by not-fl3** [not-fl3/miniquad#172]
Entrypoint for this issue: https://github.com/not-fl3/miniquad/blob/master/src/clipboard.rs#L60

On MacOs clipboard is not implemented and is falling back to a `dummy` backend. 

Some tips on implementation: as far as I know upstream sokol_app have a clipboard implementation, so the plan 
- take a look on the miniquad's clipboard api and linux/windows impls as a reference
- do a lot of copy-pasting from upstream sokol_app to native/sapp-darwin's sokol_app
- write some rust in native/sapp-darwin to match the miniquad clipboard api

**Comment by akxcv** [comment]
How about simply using https://github.com/aweinstock314/rust-clipboard/blob/master/src/osx_clipboard.rs from the `clipboard` crate? Apologies if I'm misunderstanding the intricacies of the issue somehow.
