### ISSUE TITLE
[Discussion] Using platform-specific features 

### ISSUE THREAD

**Issue by not-fl3** [not-fl3/miniquad#176]
# Compatibilities proposal

## The problem

Miniquad guarantees that the same code will work on all the supported platforms.  
When this is not true - it is always considered as a bug and should be fixed.  
The fix may involve platform specific workaround or emulation of some sort or even removing a certain feature completely.  

An example where we found a way to workaround hardware incompatibility: single-channel alpha textures: https://github.com/not-fl3/miniquad/pull/101 While webgl1 and gles3 have different single channel textures (R8 vs A8) we still can provide the same API for both and exactly the same code will work on each platform.

An example where we failed to find a workaround: https://github.com/not-fl3/miniquad/issues/166 there are no SRGB textures on some platforms and to maintain miniquad's guarantees on cross-platform support - we cant use SRGB textures.  
There are way more cases where we refuse some features because they are unavailable on some certain platform.  

## The proposal

By default miniquad still should guarantee cross-platform support. However, it should be possible to explicitly request certain features and take responsibility for the consequences.  

- `compatibilities` field in the `Conf` struct for the miniquad init. Each feature from `compatibilites` struct would be a soft requirement - enabled only if possible.  
- runtime checks for actually enabled compatibilities "dangerous" feature.  

The pipeline for such a dangerous feature would be - request desired feature and later check did it really enabled. If not - either panic or provide some fallback, but on the userland side.  

```
miniquad::start(conf::Conf {
    compatibilities: Compatibilties {
        web_webgl2: true,
        ..Default::default()
    },
    Default::default()
}, ..);

...

let shader = if ctx.compatibilities().web_webgl2 {
    // create some shader assuming "fwidth" is available
} else {
   // create the fallback shader assuming there is no "fwidth"
}
```

or 

```
miniquad::start(conf::Conf {
    compatibilities: Compatibilties {
        web_ext_srgb: true,
        ..Default::default()
    },
    Default::default()
}, ..);

...

if ctx.compatibilities().web_ext_srgb == false {
    warn!("EXT_sRGB extension not found, colors would be ruined;") // but who cares, its only and old, pre-chromium edge
}
```

## Questionable design decision

```
let color_img = Texture::new(
    ctx,
    TextureAccess::Static,
    TextureParams {
        width: 256,
        height: 256,
        format: TextureFormat::SRGBA8,
        ..Default::default()
    },
);
```

If `web_ext_srgb` was not requested - should this code panic?  
I think it should - this way the user will be aware of the problem right away and will add appropriate `compatibilities` requests right away. And the code will behave the same way everywhere, which is just what miniquad guarantees.  

But I am pretty sure that this will look quite frustrating - when its a desktop build and never supposed to run on web, but miniquad is panicking about some weird web extension.

**Comment by heilmoli** [comment]
I think it makes sense for miniquad to gurantee a minimum feature level or panic otherwise - at least then you may get a clear idea why it failed e.g. "base level feature x" or" requested feature y was not available". But its impossible to set an upper limit - miniquad on my windows machine will happily run a #version 300 es shader but it won't on wasm.  The existance of an extension may also not be indicative of the actual functionality available as extensions get merged into later GL versions (see the glsl fwidth function for example).

**Comment by nokola** [comment]
Thanks for starting this thread! I think it's very useful to have good capability/compatibility system.

For me, these are the goals of such system. I copied some of yours and added a little:
## Goals
1. Guarantee cross-platform support
2. Explicitly request certain features and take responsibility for the consequences
	- if a feature is not requested and is used in code fail to compile the program
		instead of "if a feature is not available, crash"
	- have a way to detect if the feature is available

---

Example: 
> ```rust
>         format: TextureFormat::SRGBA8,
>         ..Default::default()
>     },
> );
> ```
> 
> 
> If `web_ext_srgb` was not requested - should this code panic?
> 
> I think it should - this way the user will be aware of the problem right away and will add appropriate `compatibilities` requests right away.

I think the code above **shouldn't compile** at all. Then you don't have to worry if you missed a check. If your code compiles, it means it correctly checks compatibility and will work. I suspect we can make the above code not compile in Rust but I don't know how. Maybe something with the type system.

**Comment by nokola** [comment]
This is what I mean for example about having unsupported scenario not compile:

**OK case - compiles**
```rust
let ctx_srgb: Option<ContextSrgb> = ctx.get_srgb(); // this is how to check for compatibility

if let Some(ctx_srgb) = ctx_srgb
{
    let color_img = Texture::new_srgb(
        ctx_srgb, // OK
        TextureAccess::Static,
        TextureParams {
            width: 256,
            height: 256,    
            format: TextureFormat2::SRGBA8, // OK. Note new format
            ..Default::default()
        },
    );
}
else
{
    let color_img = Texture::new(
        ctx,
        TextureAccess::Static,
        TextureParams {
            width: 256,
            height: 256,    
            format: TextureFormat::RGBA8, // OK: old texture supported everywhere
            ..Default::default()
        },
    );
}
```

**Error case 1 - does not compile**
Someone tried to use SRGB format without checking if system supported (passing missing format)
```rust
let color_img = Texture::new(
    ctx,
    TextureAccess::Static,
    TextureParams {
        width: 256,
        height: 256,    
        format: TextureFormat::SRGBA8, // COMPILE ERROR: unknown enum member 
        ..Default::default()
    },
);
```

**Error case 2 - does not compile**
Someone tried to use srgb format without checking if system supported (passing incorrect context)
```
let color_img = Texture::new_srgb(
    ctx, // COMPILE ERROR: expected 'ContextSrgb' got 'Context' instead
    TextureAccess::Static,
    TextureParams {
        width: 256,
        height: 256,    
        format: TextureFormat2::SRGBA8,
        ..Default::default()
    },
);
```

**Comment by not-fl3** [comment]
Fixed by https://github.com/not-fl3/miniquad/pull/305
