### ISSUE TITLE
Dockerfile for notfl3/cargo-apk

### ISSUE THREAD

**Issue by nikita-skobov** [not-fl3/miniquad#181]
Hi, I was able to compile and run this on my android device using your docker image: `notfl3/cargo-apk`. 

I looked at your fork of android ndk glue: https://github.com/rust-windowing/android-rs-glue

and see that theres a Dockerfile there, so I thought maybe that's where the image came from, but I tried to build miniquad examples using the Dockerfile in your fork, but I was unable to compile. But the actual docker image `notfl3/cargo-apk` does compile.

Maybe I'm just not seeing it, but could you show me where the Dockerfile is that you used to make `notfl3/cargo-apk`?

**Comment by not-fl3** [comment]
https://github.com/not-fl3/android-rs-glue/blob/master/Dockerfile

**Comment by not-fl3** [comment]
maybe the one on dockerhub is with updated rust version (with added `rustup update` somewhere in the dockerfile)

**Comment by nikita-skobov** [comment]
Ok got it thanks
