### ISSUE TITLE
gl.js version is: 0.1.24, rust sapp-wasm crate version is: 0.1.26

### ISSUE THREAD

**Issue by GerodruS** [not-fl3/miniquad#213]
Hi!
I've created a new project with last version of macroquad and tried to make a build for webgl.
And I've got an error in browser at start:
`gl.js version is: 0.1.24, rust sapp-wasm crate version is: 0.1.26`

I'm using js bundle from here:
https://not-fl3.github.io/miniquad-samples/mq_js_bundle.js

Does somewhere there a more up-to-date version of bundle?

**Comment by PSteinhaus** [comment]
This is probably a bit late, but this should be the latest version `0.1.26` you're searching for:
https://github.com/not-fl3/macroquad/blob/master/js/mq_js_bundle.js
