### ISSUE TITLE
include readme and license file in crate source of sapp-linux and sapp-kms

### ISSUE THREAD

**Issue by remilauzier** [not-fl3/miniquad#215]
Hi. I am packaging sapp-linux and sapp-kms in fedora and they would like to have the license file and the readme file include in the source crate.
Here the fedora guideline: https://docs.fedoraproject.org/en-US/packaging-guidelines/Rust/
License: https://docs.fedoraproject.org/en-US/packaging-guidelines/LicensingGuidelines/#_license_text
Documentation: https://docs.fedoraproject.org/en-US/packaging-guidelines/#_documentation
Thanks for your time.

**Comment by not-fl3** [comment]
Hi! `sapp-linux`/`sapp-kms` are not really intended to be used without miniquad itself, so the real README would be something like "this is an internal crate, go check miniquad's readme instead". 
However, if there are some changes that may help you with packaging - I am very open to PRs!

**Comment by not-fl3** [comment]
Solved with https://github.com/not-fl3/miniquad/pull/216
