### ISSUE TITLE
Current sapp-windows (version = 0.2.17) code diverges from docs.rs code

### ISSUE THREAD

**Issue by elsid** [not-fl3/miniquad#218]
Based on https://docs.rs/crate/sapp-windows/0.2.17/source/src/lib.rs and https://github.com/not-fl3/miniquad/blob/bb54bf1ff835e8aba7a9f3b76b4a1d41cd4b5617/native/sapp-windows/src/lib.rs comparison.

https://github.com/not-fl3/miniquad/commit/bb54bf1ff835e8aba7a9f3b76b4a1d41cd4b5617 bumps sapp-windows version to 0.2.17 and it was pushed on 2021-06-14 to github but crates.io says https://crates.io/crates/sapp-windows/0.2.17 is made on 2021-05-30. So it looks like not pushed to github code was submitted for a new crate version.

**Comment by not-fl3** [comment]
Thanks for the report, published miniquad `v0.3.0-alpha.36` with the mentioned change!
