### ISSUE TITLE
Matrix Structures - Use Const Generics?

### ISSUE THREAD

**Issue by sno2** [not-fl3/miniquad#228]
Hi, I was just wondering if it might be better to instead of including the `Mat2`, `Mat3`, ect. structs for 2x2 and 3x3 matrices, respectively to use constant generics for a single 2d Matrix.  Here is what I was using within a basic matrix calculator I built in Rust for school:

```rust
struct Matrix2d<const R: usize, const C: usize> {
  rows: [[f32; C]; R],
}

impl<const R: usize, const C: usize> Matrix2d<R, C> {
	pub const fn new() -> Self {
		Self {
			rows: [[0f32; C]; R],
		}
	}
}

impl<const R: usize, const C: usize> From<[[f32; C]; R]> for Matrix2d<R, C> {
	#[inline(always)]
	fn from(rows: [[f32; C]; R]) -> Self {
		Self { rows }
	}
}
```

This would still allow for specifying places where you want a 2x2 matrix:

```rust
fn render_quadrilateral(points: Matrix2d<2, 2>) {
  // foo
}

// works fine
render_shape(Matrix2d::from([ [ 2, 4 ], [ 4, 3 ], [ 2, 8 ], [ 4, 7 ] ]));

// throws error - the second array item has a length of 1 which does not match inferred C value
render_shape(Matrix2d::from([ [ 2, 4 ], [ 4 ] ])); 
```

And also, you can handle for square matrices, i.e. finding determinant or identity, while checking if it is possible at compile-time:

```rust
impl <const S: usize> Matrix2d<S, S> {
  fn determinant() -> Option<f32>;
}
```

Also dot product:

```rust
impl <const R1: usize, const C1: usize> Matrix2d<R1, C1> {
  fn dot_product<const R2: usize>(&self, matrix: &Matrix2d<R2, R1>) -> Option<f32>;
}
```

**Comment by not-fl3** [comment]
Miniquad do not have a Matrix struct or any math whatsoever :)

I guess this issue belongs to glam-rs, which was used for miniquad's examples? 

https://github.com/bitshifter/glam-rs/
