### ISSUE TITLE
Add API to read pixel from the GPU buffer

### ISSUE THREAD

**Issue by akhilman** [not-fl3/miniquad#235]
Please add a function to read pixels from GPU buffer.

https://www.khronos.org/registry/OpenGL-Refpages/es3.0/html/glReadPixels.xhtml
https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/readPixels

**Comment by not-fl3** [comment]
We already have one: https://docs.rs/miniquad/0.3.0-alpha.36/miniquad/graphics/struct.Texture.html#method.read_pixels

**Comment by akhilman** [comment]
Ok. Sorry.
