### ISSUE TITLE
running miniquad on Android

### ISSUE THREAD

**Issue by mrazorvin** [not-fl3/miniquad#238]
Hi, just want to say thanks for amazing library. It looks like this is single lib that currently works on android. I spent entire day and tried different libraries like (glium + winit, sdl2 + glow, their forks and even some vulkan libraries) most of them are outdated or don't work with `android-ndk-rs`.
I moved from browser WebGL2 + TS + esbuild and for me is critically to be able to run dev build without complications.

Anyway I did following steps
* I installed android SDK & NDK  (version r22, according to supported targets in https://github.com/rust-windowing/android-ndk-rs)
* Look for `Android` word in miniquad issues :D 
* Found this issue https://github.com/not-fl3/miniquad/issues/185 and related repository https://github.com/not-fl3/miniquad/issues/185
* thanks for @nikita-skobov detailed readme. I installed forked version of NDK and tried to run build
* Fail: Rust said that `sapp_ANativeActivity_onCreate` must be public 
* I clone entire repository (beta version) and change function signature

Some thoughts:
* Before I did steps above i tried docker file from README, but It can't connect to emulator + every single build cost me around 10 minutes ;(, will be cool if you can add additional instructions how to connect to emulator (I provided them above) ?
* I miss patched version of latest `android-ndk-rs`. According to @nikita-skobov commits we just need to changes few lines. In nodejs when I don't want to make fork of library I use auto-patcher (after library installation), I not sure if cargo has something like this 

Questions: 
* I want to use advanced features like: 
- compressed textures (supported everywhere from WebGL2)
- 2DArrayTextures  (supported everywhere from WebGL2)
- Multiple color attachments (supported everywhere from WebGL2)
- Attribute Divisor (supported everywhere from WebGL2)
- SSBO (optionally, only android + desktop)
- Pixel Local Storage (optionally, only android + desktop)
* Could you give some advice what is the best way to add them (first 4 is critically to make application fast application and reduce draw calls and memory usage)?
* I use workspaces for forked version of `miniquad` and rust-analyzer in vscode show me +2000 of errors in `native` folder, doy you now what is the best way to supress & ignore them ?

**Comment by not-fl3** [comment]
Thats a lot of questions! 

You can find instructions for building miniquad without docker here https://macroquad.rs/tutorials/android/#a-manual-way

**Comment by mrazorvin** [comment]
> Thats a lot of questions!
> 
> You can find instructions for building miniquad without docker here https://macroquad.rs/tutorials/android/#a-manual-way

thanks for the info, that helps a lot, i suppose issue could be closed

Regarding patching: I found cargo-patch :D, so now I don't need to use a forked version of ndk
Regarding fork & rust-analyzer: I found some workaround (thanks to this issue https://github.com/rust-analyzer/rust-analyzer/issues/3975), you need to open sub-package (not root workspace) and configure add following configuration
```
{
  "rust-analyzer.checkOnSave.overrideCommand": [
    "cargo",
    "check",
    "-p=test-ndk",
    "--message-format=json"
  ]
}
```

P.S maybe you can give some advice what is the best way to enable platform specific features (to my fork), I don't care about WASM and ios platforms
