### ISSUE TITLE
wayland support

### ISSUE THREAD

**Issue by bpostlethwaite** [not-fl3/miniquad#239]
I see there has been some [discussion](https://github.com/not-fl3/miniquad/issues/8) and [effort](https://github.com/not-fl3/miniquad/pull/152) around Wayland support. 

Is Wayland support something that may be addressed soon? I'm starting a new project and looking at glium and miniquad and this is definitely a factor in that decision. Thanks!

**Comment by not-fl3** [comment]
`wayland` branch is mostly functional, but I am not sure that is going to be merged soon. 

I disappointed in wayland myself and moved back to X11, so I am not ready for maintaining it too much right now. 
But finishing wayland support is planned and will be nice to have!
