### ISSUE TITLE
Possibility/Feasibility of using Rust-GPU for Rust Shaders

### ISSUE THREAD

**Issue by Pebaz** [not-fl3/miniquad#254]
https://github.com/embarkstudios/rust-gpu

Possible? Not possible?

**Comment by not-fl3** [comment]
miniquad do not really do anything about shaders, so if rust-gpu can generate glsl - it may work. The process rust-gpu -> spirv -> glsl might be a bit cumbersome tho, and I do not really think it is a reasonable approach, miniquad is more about low-end hardware and simple shaders.

**Comment by rice7th** [comment]
Spir-V support?
