### ISSUE TITLE
Questions regarding this project

### ISSUE THREAD

**Issue by Raj2032** [not-fl3/miniquad#262]
Hi, I have some questions regarding this project:
1. Is it like Bevy where it locks me into some kind of framework (in terms of coding) using their ECS model or does it allow me to code freely. What I mean is that if you take a look at `pathbuff`

```rust
use std::path::PathBuf;

let mut path = PathBuf::new();

path.push(r"C:\");
path.push("windows");
path.push("system32");

path.set_extension("dll");
```

See how it doesn't lock me into some kind of framework, I can still code freely. Can I do this?

Am I able to do programming in the `main()` function such as game logic etc?

2. Is there support for either wgpu or vulkan?
3. In regards to [`egui-miniquad`](https://github.com/not-fl3/egui-miniquad), just like I have asked in question `1`, is it free coding style or does it lock me into some kind of framework?
4. Do you have a GUI game editor or not?

**Comment by not-fl3** [comment]
No, it does not. I would recommend checking the examples https://github.com/not-fl3/miniquad/tree/master/examples to see how miniquad code looks like.

Regarding backends I would recommend checking the readme, https://github.com/not-fl3/miniquad#supported-platforms, there is a list of platforms and graphics backends currently in use

**Comment by Raj2032** [comment]
ok thanks mate
