### ISSUE TITLE
Try to update Sokol_App.h to solve MACOS Input bug

### ISSUE THREAD

**Issue by Bibi210** [not-fl3/miniquad#268]
Hi,
In an attempt to solve this not-fl3/macroquad#357 in macroquad 
I've tried to update the Sokol_App.h file.
But i get an assert failure on the windows pixel size maybe isn't initialized anymore.

<img width="875" alt="Capture d’écran 2022-02-14 à 11 07 00" src="https://user-images.githubusercontent.com/58879980/153843479-3af25a9e-84a5-402a-b006-982f66f78304.png">
Also Miniquad Graphics::ElapsedQuery don't pass anymore
<img width="843" alt="Capture d’écran 2022-02-14 à 11 01 44" src="https://user-images.githubusercontent.com/58879980/153842652-a67ce488-2748-438c-9170-bdb60343fa9a.png">

Since updating the whole Sokol_App File might be too much for this small issue I've tried to just update the keydown function but i think its just a bad idea.

Even when i just patch the ```keydown ```function as SOKOL developper did in the master branch the ```key_up_event``` is still not detected by Miniquad

Thank you for your time

**Comment by not-fl3** [comment]
no more sokol C code in the miniquad source tree :)
