### ISSUE TITLE
"GLX: failed to create GL context" under Crostini on an ARM-based Chromebook

### ISSUE THREAD

**Issue by RustigeMan** [not-fl3/miniquad#269]
I'm trying to run the examples on Debian Bookworm under Crostini on an ARM-based Chromebook. I get the following error message:

"GLX: failed to create GL context"

**Comment by not-fl3** [comment]
What OpenGl version does this Chromebook have? miniquad requires gl3.2+ (at this moment, gl2 is coming very very soon!)

**Comment by RustigeMan** [comment]
It has OpenGL 2.1 and OpenGL ES 3.1 (Mesa 21.2.6). So I guess that explains it. Thanks.
