### ISSUE TITLE
Zemeroth port, unlike itch.io Zemeroth, doesn't react to touch

### ISSUE THREAD

**Issue by Zireael07** [not-fl3/miniquad#30]
The only niggle I can see now :P it renders perfectly on both web and mobile.

**Comment by not-fl3** [comment]
Nice!
This version of zemeroth does not support touches, which is unfortunate, but not quite related to miniquad. 
Thanks for testing anyway, glad it works!

**Comment by Zireael07** [comment]
Where should file a feature request for touch support then?

**Comment by not-fl3** [comment]
I think `good-web-game` can emulate mouse_down/up events on the platforms when only touches are available. 
Did it locally, it works for zemeroth, will publish soon. So right here was a good place for the feature request!
