### ISSUE TITLE
Astroblasto demo doesn't seem to work on my phone (unlike Zemeroth)

### ISSUE THREAD

**Issue by Zireael07** [not-fl3/miniquad#31]
Since there's no way to open the console in web browser, afaik, there should be a pop-up or something in case of errors on the wasm target (can't compile? can't find file? no idea what is going wrong since Zemeroth demo works).

**Comment by not-fl3** [comment]
Works on my machine! 

Updated astroblasto demo however. There was unstripped 17M binary, so maybe it was just a loading time issue?

**Comment by not-fl3** [comment]
Lets hope it works now! :)
