### ISSUE TITLE
font rendering

### ISSUE THREAD

**Issue by PonasKovas** [not-fl3/miniquad#37]
is it possible? Any plans?

**Comment by not-fl3** [comment]
Yes, https://github.com/not-fl3/miniquad_text_rusttype

however miniquad is a low level opengl wrapper, if you need a lot of  higher-level features - take a look on some miniquad-based game frameworks, like

more stable: https://github.com/not-fl3/good-web-game
or 
less stable: https://github.com/not-fl3/macroquad/

both have fonts rendering included out of the box
