### ISSUE TITLE
No option to disable VSync

### ISSUE THREAD

**Issue by ccptr** [not-fl3/miniquad#383]
This seems like the perfect library for what I want to do, but I need to disable VSync. Since this would likely be a breaking change, could it be added for version 4.0?

If needed I could attempt to implement it if you pointed me in the right direction.

**Comment by not-fl3** [comment]
There is no way to reliable disable vsync across all the platforms. 

Even if it would be possible, driver settings could always override vsync preferences of the app, so it is never a good idea to depend on vsync being off. 

There is a way to give an advice for a graphics context to disable vsync, but it is not guranteed to work everywhere

```
fn window_conf() -> Conf {
    Conf {
        window_title: "Test".to_owned(),
        platform: macroquad::miniquad::conf::Platform {
            swap_interval: Some(0),
            ..miniquad::conf::Platform::default()
        },
        ..Default::default()
    }
}
```

**Comment by ccptr** [comment]
That's the case anyway, yet the option to disable it (or to request to disable it, if possible at all) exists in games regardless of whether it can actually can be or not. Thanks for the code though! Don't work with graphics a lot; forgot it's actually a called a swap interval (:
