### ISSUE TITLE
Crash when sending request_screen_size on MacOS

### ISSUE THREAD

**Issue by alters-mit** [not-fl3/miniquad#389]
This is new as of miniquad 0.4

```
thread 'main' panicked at 'already borrowed: BorrowMutError', <...>/miniquad-0.4.0-alpha.5/src/native/macos.rs:53:27
```

**Comment by not-fl3** [comment]
should be fixed on `0.4.2` 

yes, there is a probability that I broke everything again, it was a big fix, so would really appreciate if you'll retest everything again :| 

Sorry for so many broken things, but that was the last big change for a while(hopefully haha)

Feel free to reopen if this is not fixed!
