### ISSUE TITLE
Regression: incorrect render size on Android

### ISSUE THREAD

**Issue by andreymal** [not-fl3/miniquad#399]
Commit https://github.com/not-fl3/miniquad/commit/f46c5dd5d69b6563919f19de974f89024c9a6afe introduced a bug: if there are no resize events from Android, miniquad thinks that the window size is 800x600 (or any other value defined in conf::Conf)

For example, screenshot of `basic_shapes.rs` from macroquad:

![miniquad](https://github.com/not-fl3/miniquad/assets/3236464/ddc705ca-1fe3-457a-a4b9-46b0219201a7)

**Comment by not-fl3** [comment]
Thanks for the report, should be fixed in 0.4.0-alpha.8 (https://github.com/not-fl3/miniquad/commit/15420dc65896f6b6f47ce1cbcd6bc9db687a70a0)
