### ISSUE TITLE
Texture wrapping set incorrectly for y-axis (Simple Fix)

### ISSUE THREAD

**Issue by sokorototo** [not-fl3/miniquad#429]
https://github.com/not-fl3/miniquad/blob/65b64ad8d13c4ef5d4d26549c59c617099481932/src/graphics/gl.rs#L836

Replace `wrap_x` with `wrap_y`

**Comment by not-fl3** [comment]
looks like a bug, feel free to make a PR!

**Comment by sokorototo** [comment]
Unfortunately I can't create a fork and open a PR. I discovered this bug while porting a fork of `miniquad` to `wasm-bindgen`. You can check out the repo [miniquad-wasm-bindgen](https://github.com/sokorototo/miniquad-wasm-bindgen) if you are interested.

**Comment by profan** [comment]
this looks like it has been fixed, can probably be closed?
