### ISSUE TITLE
Can it be used to make a text editor?

### ISSUE THREAD

**Issue by rawhuul** [not-fl3/miniquad#451]
Hi,

Although it is possible to make a text editor using `miniquad`, but is it a good idea? I made one using SDL2 in past, and it was good enough from performance and battery perspective. What are cons of using `miniquad` while making a text editor? I just want it to be performant and low memory usage

**Comment by birhburh** [comment]
Main feature is of course build time, but question is not about it

Recently new feature [`blocking_event_loop`](https://github.com/not-fl3/miniquad/pull/437) was added to miniquad to reduce CPU usage on idle (And battery usage yes)

`miniquad` by itself has no text rendering abilities. `macroquad` has, but it is more like game engine than general UI framework (but it has UI abilities)

there is also [egui-miniquad](https://github.com/not-fl3/egui-miniquad) implementation for relatively easier GUI programming. But for now it has no `blocking_event_loop` ability (I'll try to look into this)

Miniquad has no API to partially redraw screen to, for example, redraw only cursor that blinking. But most editors written in rust and underlying libs also has no this feature for now. And on modern GPUs there is not much a difference in perfomance for drawing full or part of the screen.

Memory usage is good, but it means that there is not enough functionality and you will need write a lot yourself or use additional libraries. But `macroquad` or `egui-miniquad` may be enough for a text editor and they use not much memory. But I have no measures myself.

**Comment by rawhuul** [comment]
Thanks, currently I am using SDL2, will try to replace it with `miniquad` and will let you know how it turns out
