### ISSUE TITLE
Support for pixel arithmetic for RGB and alpha components separately

### ISSUE THREAD

**Issue by nokola** [not-fl3/miniquad#55]
The BlendState today only supports the equivalent of BlendFactor for argb (glBlendFunc):
```rust
type BlendState = Option<(Equation, BlendFactor, BlendFactor)>;
```

Ideally, it would support separate RGB and alpha blends (equivalent to glBlendFuncSeparate):
```rust
...
    pub src_rgb: BlendFactor,
    pub dst_rgb: BlendFactor,
    pub src_alpha: BlendFactor,
    pub dst_alpha: BlendFactor,
```

**Comment by not-fl3** [comment]
Yes, good catch, there should be separate `color_blend` and `alpha_blend`

**Comment by nokola** [comment]
Fixed by above PR
