### ISSUE TITLE
Can't run example

### ISSUE THREAD

**Issue by AKholetsky** [not-fl3/miniquad#56]
= note: offscreen.53ypclmuyuk0jfd.rcgu.o : error LNK2019: unresolved external symbol glUniform1iv referenced in function _ZN8miniquad8graphics7Context14apply_uniforms17h826f507f04b51288E
          offscreen.53ypclmuyuk0jfd.rcgu.o : error LNK2019: unresolved external symbol glUniform2iv referenced in function _ZN8miniquad8graphics7Context14apply_uniforms17h826f507f04b51288E
          offscreen.53ypclmuyuk0jfd.rcgu.o : error LNK2019: unresolved external symbol glUniform3iv referenced in function _ZN8miniquad8graphics7Context14apply_uniforms17h826f507f04b51288E
          offscreen.53ypclmuyuk0jfd.rcgu.o : error LNK2019: unresolved external symbol glUniform4iv referenced in function _ZN8miniquad8graphics7Context14apply_uniforms17h826f507f04b51288E
          E:\Projects\Rust\miniquad\target\debug\examples\offscreen.exe : fatal error LNK1120: 4 unresolved externals

error: aborting due to previous error

error: could not compile `miniquad`.

Caused by:
  process didn't exit successfully: `rustc --crate-name offscreen --edition=2018 'examples\offscreen.rs' --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C debuginfo=2 --cfg 'feature="default"' -C metadata=43a6cd1433160286 --out-dir 'E:\Projects\Rust\miniquad\target\debug\examples' -C 'incremental=E:\Projects\Rust\miniquad\target\debug\incremental' -L 'dependency=E:\Projects\Rust\miniquad\target\debug\deps' --extern 'glam=E:\Projects\Rust\miniquad\target\debug\deps\libglam-1b36325fb75c82d6.rlib' --extern 'miniquad=E:\Projects\Rust\miniquad\target\debug\deps\libminiquad-ef5f0da1371f9c36.rlib' --extern 'sapp_windows=E:\Projects\Rust\miniquad\target\debug\deps\libsapp_windows-36ac608f4451b9d6.rlib' -L 'native=E:\Projects\Rust\miniquad\target\debug\build\sapp-windows-249a45c963a76aba\out'` (exit code: 1)

**Comment by not-fl3** [comment]
Thanks for report, can confirm, the problem is on miniquad's side, working on it

**Comment by nokola** [comment]
Sorry about the issue! It's a bug I introduced with earlier PR. Will be more careful in the future. Not sure why it worked on my machine before, but when I start from clean enlistment I get the same error now

**Comment by not-fl3** [comment]
No problems!
The real issue here is that CI did not catch this and was green.

**Comment by AKholetsky** [comment]
Local build of the project proceeds normally. Error only when running examples at the linking stage. I could be wrong, but doesn’t CI just make cargo build ?

**Comment by nokola** [comment]
This fixes it for me on Windows MSVC:
```diff
--- a/native/sapp-windows/external/sokol/sokol_app.h
+++ b/native/sapp-windows/external/sokol/sokol_app.h
@@ -3366,6 +3366,26 @@ static PFN_glUniform1i _sapp_glUniform1i;
 void  glUniform1i(GLint location, GLint v0) {
     _sapp_glUniform1i(location, v0);
 }
+typedef void  (GL_APIENTRY *PFN_glUniform1iv)(GLint location, GLsizei count, const GLint * value);
+static PFN_glUniform1iv _sapp_glUniform1iv;
+void  glUniform1iv(GLint location, GLsizei count, const GLint * value) {
+    _sapp_glUniform1iv(location, count, value);
+}
+typedef void  (GL_APIENTRY *PFN_glUniform2iv)(GLint location, GLsizei count, const GLint * value);
+static PFN_glUniform2iv _sapp_glUniform2iv;
+void  glUniform2iv(GLint location, GLsizei count, const GLint * value) {
+    _sapp_glUniform2iv(location, count, value);
+}
+typedef void  (GL_APIENTRY *PFN_glUniform3iv)(GLint location, GLsizei count, const GLint * value);
+static PFN_glUniform3iv _sapp_glUniform3iv;
+void  glUniform3iv(GLint location, GLsizei count, const GLint * value) {
+    _sapp_glUniform3iv(location, count, value);
+}
+typedef void  (GL_APIENTRY *PFN_glUniform4iv)(GLint location, GLsizei count, const GLint * value);
+static PFN_glUniform4iv _sapp_glUniform4iv;
+void  glUniform4iv(GLint location, GLsizei count, const GLint * value) {
+    _sapp_glUniform4iv(location, count, value);
+}
 typedef void  (GL_APIENTRY *PFN_glDisable)(GLenum cap);
 static PFN_glDisable _sapp_glDisable;
 void glDisable(GLenum cap) {
@@ -3588,6 +3608,10 @@ _SOKOL_PRIVATE  void _sapp_win32_gl_loadfuncs(void) {
     _SAPP_GLPROC(glDrawElementsInstanced);
     _SAPP_GLPROC(glVertexAttribPointer);
     _SAPP_GLPROC(glUniform1i);
+    _SAPP_GLPROC(glUniform1iv);
+    _SAPP_GLPROC(glUniform2iv);
+    _SAPP_GLPROC(glUniform3iv);
+    _SAPP_GLPROC(glUniform4iv);
     _SAPP_GLPROC(glDisable);
     _SAPP_GLPROC(glColorMask);
     _SAPP_GLPROC(glBindBuffer);
```

Not sending PR since @not-fl3 may be working on it already and I have trouble building the GNU toolchain on Windows right now.

**Comment by not-fl3** [comment]
Thanks! Nice, I have problems with msvc, so I can test with gnu toolchain! :) 

I am still stuck a bit with gh actions: https://github.com/not-fl3/miniquad/runs/569502802?check_suite_focus=true

```
 Downloading crates ...
##[error]The operation was canceled.
```
no idea why it is canceled. Any ideas welcome! But I hope I'll fix it somehow eventually :)

**Comment by nokola** [comment]
Nice between us two we have the toolchains covered :)
re: cancelled - not sure, maybe some GitHub build limit or temporary issue?

**Comment by nokola** [comment]
Added pull request #57

**Comment by not-fl3** [comment]
https://github.com/not-fl3/miniquad/runs/571472293?check_suite_focus=true
https://github.com/not-fl3/miniquad/pull/58

apparently it works and now we have the right errors on CI!

**Comment by AKholetsky** [comment]
Works on windows.
