### ISSUE TITLE
ubuntu build error: "/usr/bin/ld: cannot find -lGL"

### ISSUE THREAD

**Issue by not-fl3** [not-fl3/miniquad#6]
It should be possible to build `miniquad` without any `-dev` ubuntu packages. 

Dynamic libGL linking should be used. In other words - remove `-lGL` from sapp-linux's build.rs and fix all the errors.

**Comment by not-fl3** [comment]
Right now the following packages are required on fresh Ubuntu: libx11-dev, libXi-dev, libgl1-mesa-dev

However, the non-dev versions are already here.
There are two options to solve this

- Write `apt install libx11-dev libXi-dev libgl1-mesa-dev` to README :) 
- Use dlsym and macro magic to load symbols from those libraries with rust. Like its done in `x11-rs` https://github.com/daggerbot/x11-rs/blob/master/x11-dl/src/link.rs 
https://github.com/erlepereira/x11-rs/blob/master/src/xlib.rs#L41

The second option is way more complicated - basically, it is rewriting part of the linker, that is already here.  
On the other hand - building on a fresh ubuntu box without any native dependencies is very nice. 

I think that this requires too much effort just to workaround ubuntu's .so/.so.6 packages distinction.

**Comment by koalefant** [comment]
Arch user here: not a problem at all :smile:

**Comment by not-fl3** [comment]
Ok, not worth it. 
Added `apt install libx11-dev libxi-dev libgl1-mesa-dev` for ubuntu users into readme :)
