### ISSUE TITLE
Random is not seeded on Linux

### ISSUE THREAD

**Issue by tversteeg** [not-fl3/miniquad#65]
I have to manually call the following to seed it:

```rust
extern "C" {
    // Seed random when on Linux
    fn srand(input: u32);
}

//..
unsafe {
	srand(miniquad::date::now() as u32);
}
```

**Comment by not-fl3** [comment]
That is true, `rand` is inconsistent between desktop and wasm. JS random is not seedable, while libc random is seedable prng :( 

For seedable random I would recommend using https://github.com/not-fl3/quad-rand, it has a bit more features and works in exactly the same way on PC and wasm.

**Comment by tversteeg** [comment]
Right, shouldn't the `rand` function be deprecated in that case?

**Comment by not-fl3** [comment]
I agree. Thanks for your service, libc rand :wave: 

https://github.com/not-fl3/miniquad/pull/66
