### ISSUE TITLE
Support multisampling

### ISSUE THREAD

**Issue by tversteeg** [not-fl3/miniquad#72]
Is there a possibility multi-sampling could be supported? I would like to render vector graphics using lyon and having multisampling would save a lot of work having to implement an anti-aliasing part myself: https://www.khronos.org/opengl/wiki/Multisampling

**Comment by not-fl3** [comment]
with `Conf::sample_count` > 1 OpenGL's MSAA should be enabled 
https://github.com/not-fl3/miniquad/blob/master/src/conf.rs#L78

**Comment by tversteeg** [comment]
Awesome, I didn't see that field, thanks!

**Comment by nokola** [comment]
btw I'm working on AA library for vector graphics (port of NanoVG), will post once done
