### ISSUE TITLE
Leak in instancing example.

### ISSUE THREAD

**Issue by Slyklaw** [not-fl3/miniquad#9]
GPU utilization slowly rises, until the following panic occurs after a few minutes.

`thread 'main' panicked at 'assertion failed: size <= self.size', src\graphics.rs:1194:9`

Win10 native build.

**Comment by not-fl3** [comment]
Thanks for report! Fixed in https://github.com/not-fl3/miniquad/commit/6f9c6665a8cb8302c95a104df2f45b60393a1925
