### ISSUE TITLE
GamesShell support

### ISSUE THREAD

**Issue by Bombfuse** [not-fl3/miniquad#90]
I thought it might be worthwhile to open an issue tracking this, let me know if this isn't a good place for this.

The [gameshell ](https://www.clockworkpi.com/gameshell)is basically a raspberry pi gameboy. It'd be cool to get miniquad working on it so I first got it up on [Raspberry pi,](https://github.com/not-fl3/miniquad/issues/85) and am now working on getting it to the gameshell.

Currently facing this issue

```
/lib/arm-linux/gnueabihf/libm.so.6: version `GLIBC_2.27' not found (required by ./gameshell-project)
/lib/arm-linux/gnueabihf/libc.so.6: version `GLIBC_2.28' not found (required by ./gameshell-project)
```

**Comment by Bombfuse** [comment]
Realized I'm on Clockwork OS 0.4, need to update to the latest 0.5 to try again.

**Comment by Mubelotix** [comment]
That is a common Rust issue. Try compiling your program directly on the target machine.

**Comment by Bombfuse** [comment]
Oh yikes, is there a way to build a binary for it without compiling an entire game on the Gameshell? I have a feeling it might get way too hot compiling

**Comment by PSteinhaus** [comment]
I saw your game running on a GameShell the other day over on Discord (Congratulations ^^).
Can this be closed then? Perhaps some words on how you finally got it to run would be nice for anyone stumbling over this wanting to do the same : )

**Comment by Bombfuse** [comment]
Yah I was able to get it working! Unfortunately the only way to get it running is through software rendering, so it requires a few parameters to run your game.

Steps

1. Compile your game directly on the GameShell
2. Copy your executable and assets into a new directory (just for the sake of cleanliness)
3. Create a shell (`.sh`) file with the following content in that directory
```sh
export DISPLAY=:0.0
MESA_GL_VERSION_OVERRIDE=3.3 ./{your game exe name here}
```
4. Run the sh script on your GameShell!


Note: There are methods of creating an icon on the gameshell launcher that runs this bash script, that is how you make your game runnable from the launcher itself.

FUTURE: I believe that when GLES2 is implemented for Miniquad we should be able to drop the software rendering requirement
