### ISSUE TITLE
event.preventDefault() for key presses

### ISSUE THREAD

**Issue by koalefant** [not-fl3/miniquad#91]
Hi, not sure if that is a big deal for anyone else, but I got multiple bugs because I would not call preventDefault on a needed event key. For example: 
- people would call F1/F5 because it changes weapons in some other game. 
- Use Backspace, and apparently it is Back on Firefox on some platforms. 
- Arrow Keys would cause scrolling of main page on itch.io. 

That is something I have to patch gl.js for locally, and I wonder if it would make sense to have this actually in the API somehow, or just a way to specify these externaly.

Also I wonder if `into_sapp_keycode()` is intentionally have small selection of keys, as I have to update it manually and had thoughts of just adding everything there and creating a pull request...

**Comment by not-fl3** [comment]
> Also I wonder if into_sapp_keycode() is intentionally have small selection of keys, as I have to update it manually and had thoughts of just adding everything there and creating a pull request...

it was just not done yet, I will appreciate the pull request! 

> That is something I have to patch gl.js for locally, and I wonder if it would make sense to have this actually in the API somehow, or just a way to specify these externally.

I do not have an opinion here, to be honest. Just for reference - `sokol_app` used to prevent all the special keys, but forwarded to browser all the character keys. https://github.com/floooh/sokol/blob/master/sokol_app.h#L2610
But I am totally fine to implement this when we will actually need this and accept the PR with preventDefault for all the keys for now.

**Comment by koalefant** [comment]
Thanks for the quick answer! I was also not sure about preventing all keys as it could inhibit browser hotkeys that may appear otherwise useful.

**Comment by not-fl3** [comment]
Fixed with https://github.com/not-fl3/miniquad/pull/99`
