### ISSUE TITLE
Community chatgroup

### ISSUE THREAD

**Issue by not-fl3** [not-fl3/miniquad#93]
I like the format of chat for some real-time questions and discussions. 

Just set up discord server: https://discord.gg/WfEp6ut

Any opinions on that? Do we need a bridge to the matrix? Any other preferred protocols? 

I like discords because of the nice rooms inside the server, but I do believe in the importance of open protocols and servers for communication so am interested in bridges to any other protocol.

**Comment by tversteeg** [comment]
I like the idea a lot but I prefer Matrix.

**Comment by not-fl3** [comment]
Ok, let me try to build a bridge :)

**Comment by not-fl3** [comment]
#quad-general:matrix.org is now bridget to #miniquad on discord. 
The rest room awaits bridges, but lets just hang out in #miniquad for now :)

**Comment by Bombfuse** [comment]
Looks like the discord invite is expired

**Comment by not-fl3** [comment]
Thanks for report, this one supposed to be permanent: https://discord.gg/WfEp6ut

**Comment by not-fl3** [comment]
Fixed with https://github.com/not-fl3/miniquad/pull/112
